language: java
#ant test
jdk:
  - oraclejdk7
  - openjdk6
  - openjdk7
  - oraclejdk7
cache:
  directories:
    - liferay
before_install: 
  - wget 'https://sourceforge.net/projects/lportal/files/Liferay%20Portal/6.1.2%20GA3/liferay-portal-glassfish-6.1.2-ce-ga3-20130816114619181.zip/download' -O liferay.zip
  - mkdir liferay
  - unzip liferay.zip -d liferay
  - export LIFERAY_HOME=liferay/liferay-portal-6.1.2-ce-ga3
  - ls -lht $LIFERAY_HOME/*
  - chmod +x liferay/liferay-portal-6.1.2-ce-ga3/glassfish-3.1.2.2/bin/*
  - wget 'http://sourceforge.net/projects/ctsciencegtwys/files/catania-grid-engine/1.5.8/Liferay6.1/GridEngine_v1.5.8.zip/download' -O GridEngine.zip
  - unzip GridEngine.zip -d gridengine
  - mv gridengine/GridEngine_v1.5.8/GridEngineLogConfig.xml $LIFERAY_HOME/glassfish-3.1.2.2/domains/domain1/config
  - mv gridengine/GridEngine_v1.5.8/* $LIFERAY_HOME/glassfish-3.1.2.2/domains/domain1/lib
  - unzip -d gridengine GridEngine.zip
  - $LIFERAY_HOME/glassfish-3.1.2.2/bin/asadmin start-domain domain1
  - $LIFERAY_HOME/glassfish-3.1.2/bin/asadmin enable-secure-admin
  - sudo apt-get install mysql-server
  - cp scripts/portal-ext.properties $LIFERAY_HOME
  - sudo mkdir -p /etc/grid-security
  - wget 'http://grid.ct.infn.it/cron_files/grid_settings.tar.gz' -O grid_settings.tar.gz
  - sudo tar xvfz grid_settings.tar.gz -C /etc/grid-security/
before_script:
  - mysql -u root scripts/config_liferay_database
  - wget 'http://sourceforge.net/projects/ctsciencegtwys/files/catania-grid-engine/1.5.8/Database/UsersTrackingDB.sql/download' -O UsersTrackingDB.sql
  - mysql -u root < UsersTrackingDB/UsersTrackingDB.sql 
  - cd liferay/liferay-portal-6.1.2-ce-ga3/glassfish-3.1.2.2/portlets/
install: 
  - ant deploy
notifications:
  email:
    recipients:
      - brucellino@gmail.com
